version: '3'
services:
   
  # start mavros via radarku/mavros
  mavros:
    image: radarku/mavros
    network_mode: "host"
    tty: true
    environment:
      - DISPLAY
      - FCUURL=udp://:14560@localhost:14555
